</br>
<div style="display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #555555; padding-bottom: 15px; margin-bottom: -8px;">
    <div style="width: 50%;">
        <h2>
            <span style="color: #B30033;">▍</span>Práctica 2:
        </h2>
        <h1 style="margin-top: -10px;">
            Aprendizaje y selección de modelos de clasificación.
        </h1>
    </div>
    <div style="width: 50%; text-align: right;">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-top: 30px;">
            <div style="width: 20%;"></div>
            <div style="width: 80%; border-left: 2px solid #555555; padding-left: 20px;">
                <div style="margin-bottom: 20px;">
                    <p style="margin: 0; font-size: 1.4em; font-weight: bold;">
                        Minería de Datos, 2025-26
                    </p>
                </div>
                <div style="margin-top: 8px; text-align: right;">
                    <span style="font-size: 1em; color: #D0D0D0;">
                        José Antonio Gámez Martín
                    </span>
                    <a href="mailto:Jose.Gamez@uclm.es" style="text-decoration: none; color: #888888; font-size: 0.8em; padding-left: 15px;">
                        ✉ Jose.Gamez@uclm.es
                    </a>
                </div>
                <div style="margin-top: 8px; text-align: right;">
                    <span style="font-size: 1em; color: #D0D0D0;">
                        Pablo Torrijos Arenas
                    </span>
                    <a href="mailto:Pablo.Torrijos@uclm.es" style="text-decoration: none; color: #888888; font-size: 0.8em; padding-left: 15px;">
                        ✉ Pablo.Torrijos@uclm.es
                    </a>
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div style="border-bottom: 2px solid #555555; padding-bottom: 25px; margin-bottom: 10px">
    <div style="display: flex; align-items: center; margin-bottom: 10px;">
        <span style="color: #B30033; font-size: 1.5em; margin-right: 10px;">▍</span>
        <h3 style="margin: 0; font-size: 1.4em; font-weight: bold">
            Estudiante
        </h3>
    </div>
    <ul style="list-style-type: none; padding-left: 28px; margin: 0;  font-size: 1.1em">
        <li>Marcos López Gómez</li>
    </ul>

</div>

## 1. Introducción

El objetivo de esta práctica es construir sobre el trabajo realizado en la Práctica 1. Se aplicarán y compararán diversos modelos de clasificación supervisada, utilizando validación cruzada y ajuste de hiperparámetros, para seleccionar el modelo más eficaz en la predicción del abandono estudiantil.

Para ello, continuaréis utilizando los mismos conjuntos de datos de la práctica anterior (`uclm_student_train.csv` y `uclm_student_test.csv`). El `Pipeline` de preprocesamiento desarrollado en la Práctica 1 servirá como base para el entrenamiento de los modelos (aunque podéis modificarlo).

Tendréis que explorar y evaluar los modelos de clasificación introducidos en el notebook complementario (`Material Práctica 2 - Modelos y Selección.ipynb`), junto con al menos un algoritmo adicional investigado de forma independiente, el cual tendréis que explicar más detalladamente. El rendimiento se evaluará rigurosamente mediante validación cruzada, y técnicas como `GridSearchCV` para encontrar la configuración óptima de hiperparámetros.

El modelo final seleccionado se utilizará para generar predicciones en el conjunto de prueba y participar en la competición de Kaggle.

### 1.1. Recordatorio: competición en Kaggle

La evaluación final se realizará mediante una competición privada en Kaggle. El objetivo es maximizar la métrica **F1-Score**, una medida robusta que tiene en cuenta tanto la precisión como la exhaustividad, especialmente útil en casos con clases desbalanceadas.

* **Enlace a la competición**: https://www.kaggle.com/t/16fef7f5d88c4dd399f8bad259c55947

Los equipos con mejor rendimiento en el *private leaderboard* recibirán una bonificación en la nota final:
* **1er puesto**: +0.75 puntos.
* **2º puesto**: +0.5 puntos.
* **3er puesto**: +0.25 puntos.

**Nota**: Las bonificaciones están sujetas a la revisión del código y la metodología. Se podrá requerir una justificación del enfoque para verificar la originalidad y la comprensión del trabajo.

<div style="border-bottom: 2px solid #555555; padding-bottom: 15px; margin-bottom: 10px"></div>

## 2. Carga de Datos y Preprocesamiento Base

Como punto de partida, cargaremos los datos igual que en la Práctica 1:

In [49]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

semilla=2025 # Fijo la semilla

df_train = pd.read_csv('uclm_student_train.csv')
df_train

,id,nombre,nacimiento,provincia,residencia_id,trabaja,horas_trabajo,bachillerato,nota_acceso,modalidad,creditos_a1,superados_a1,nota_s1,satisfaccion,horas_moodle,posts_foro,uso_biblioteca,eventos,tutorias,comentarios,numero_fav,talla_zapato,color_fav,meses_matriculado,grupo_trabajo,abandono
0,TO-2010-GCA531,Graciano Cano Alsina,1992-05-06,Albacete,E1-P02-H04,0,NaN,Científico,6.08,Tiempo completo,60,60,8.16,4.32,~7.2 horas,2,11,1,4,relacion correcto con compañeros,71,43,Azul oscuro,6,GR10335,1
1,CU-2016-MBP239,María Belén Polo,1998-10-31,Cuenca,E2-P03-H06,0,NaN,CIENCIAS PURAS,8.12,Tiempo completo,60,60,9.09,4.05,~11.8 horas,13,2,2,0,Uso normal de la plataforma Moodle,22,38,Coral claro,6,GR13813,0
2,CR-2010-JS201,Judith Sáenz,1992-03-11,Ciudad Real,NaN,0,NaN,Ciencias Puras,10.59,Tiempo completo,60,54,7.99,3.88,~8.8 horas,6,14,2,3,NaN,69,37,Violeta oscuro,6,GR02505,0
3,TO-2016-CDB602,Casandra de Bautista,1998-11-03,Toledo,E1-P04-H18,0,NaN,Humanidades,7.85,Tiempo completo,60,48,7.27,3.81,~8.7 horas,0,0,2,3,Relacion adecuado con compañeros.,3,34,Rosa profundo,6,GR14887,0
4,AB-2011-CAA364,Carlito Alvarado Anaya,1993-12-22,Albacete,NaN,0,NaN,ECONÓMICO,10.23,Tiempo completo,60,60,8.45,4.08,~9.6 horas,16,6,2,3,ha mejorado notablemente en asignaturas troncales,19,39,Coral claro,5,GR09244,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40540,AB-2011-CB913,Cecilia Bosch,1993-04-14,Albacete,NaN,0,NaN,CIENCIAS SOCIALES,8.64,Tiempo completo,60,36,5.52,2.94,~1.1h,8,0,3,0,NaN,23,39,Rojo violeta medio,6,GR15949,1
40541,TO-2011-WRL313,Wilfredo Roda Lerma,1987-11-12,Toledo,NaN,1,NaN,Económico,10.59,Tiempo completo,60,60,9.00,4.05,~11.5 horas,8,2,3,2,NaN,76,40,Amarillo,6,GR11547,0
40542,CR-2017-JA946,Javi Acuña,1999-09-05,Ciudad Real,NaN,0,NaN,TECNOLÓGICO,10.41,Tiempo completo,60,54,NaN,3.52,~5.1 horas,3,8,4,4,Expresa dudas sobre continuar los estudios.,24,40,Gris claro,4,GR00625,1
40543,AB-2010-TRM306,Teresita Rodrigo Morera,1992-06-23,Albacete,NaN,0,NaN,Económico,10.15,Tiempo completo,60,54,7.36,3.70,~8.0 horas,10,3,4,0,NaN,39,38,Azul real,6,GR06859,0
40544,CU-2012-OTB162,Odalys Talavera Baena,1994-08-04,Cuenca,NaN,0,NaN,CCSS,7.78,Tiempo completo,60,60,8.92,4.28,"~9,7 horas",0,9,3,3,Entrega adecuada de tareas.,44,38,Negro,6,GR07618,0

In [22]:
df_test = pd.read_csv('uclm_student_test.csv')
df_test

,id,nombre,nacimiento,provincia,residencia_id,trabaja,horas_trabajo,bachillerato,nota_acceso,modalidad,creditos_a1,superados_a1,nota_s1,satisfaccion,horas_moodle,posts_foro,uso_biblioteca,eventos,tutorias,comentarios,numero_fav,talla_zapato,color_fav,meses_matriculado,grupo_trabajo
0,AB-2019-FEM764,Fabiola Espejo Marín,2002-01-12,Ciudad Real,E1-P01-H01,0,NaN,CCSS,10.17,Tiempo completo,60,48,7.74,3.81,~11.0 horas,16,14,5,5,Expresa dudas sobre su vocacion.,43,40,Violeta sonrojado pálido,6,GR01091
1,TO-2018-ALL744,Arsenio Lucas Llanos,2000-06-13,Toledo,NaN,0,NaN,Letras,9.16,Tiempo completo,60,48,6.99,3.28,~6.8 horas,2,5,5,1,NaN,88,40,Cian,6,GR02931
2,AB-2018-ZSD099,Zaira Salvà Dominguez,2000-09-25,Albacete,NaN,0,NaN,Ciencias Puras,8.91,Tiempo completo,60,60,8.28,4.48,10.0,12,2,6,2,Busca activamente prácticas y oportunidades pr...,96,39,Gris oscuro,3,GR06795
3,CR-2019-TCS733,Tatiana Celia Solano Tejera,2001-06-05,Ciudad Real,NaN,0,NaN,Letras,9.29,Tiempo completo,60,24,3.96,1.86,~0.8 horas,10,6,3,1,NaN,62,38,Blanco lavanda,6,GR06712
4,CR-2018-VBV597,Victoriano Benavente Vilaplana,2000-06-18,Ciudad Real,NaN,0,NaN,Letras,5.00,Tiempo completo,60,0,2.85,1.26,~5.9 horas,17,2,2,0,NaN,98,44,Azul Alicia,2,GR01653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9582,AB-2019-AAM365,Albino Acero Múgica,2002-02-14,Albacete,NaN,0,NaN,Tecnológico Industrial,9.38,Tiempo completo,60,30,4.74,2.20,~4.2 horas,11,1,5,0,NaN,98,41,Marrón siena,6,GR13835
9583,AB-2019-MC507,Marina Calleja,2002-01-07,Albacete,NaN,0,NaN,CCSS,6.41,Tiempo completo,60,60,9.52,4.97,~8.4 horas,3,7,6,2,Asistencia constante a clases.,33,38,Amarillo,6,GR14729
9584,AB-2019-MNC716,Morena Noelia Castell Amor,2001-04-05,Albacete,NaN,0,NaN,Letras,9.60,Tiempo completo,60,24,5.09,2.35,7.8,2,9,2,2,Habla de cambiar de ciudad por motivos persona...,96,35,Azul anciano,6,GR11046
9585,AB-2018-ICH450,Isidora Cabrera Hoyos,2001-02-09,Albacete,NaN,1,NaN,CCSS,9.79,Tiempo completo,60,48,7.05,3.59,11.5,12,1,2,2,NaN,82,37,Blanco,6,GR10480
9586,CU-2019-CL671,Carmen Lluch-Vega,2001-08-03,Cuenca,NaN,0,NaN,Artes,6.15,Tiempo completo,60,60,8.59,4.40,~7.2 horas,4,12,0,0,NaN,52,37,Verde mar claro,6,GR03195

Y a partir de aquí reutilizaremos el pipeline de preprocesamiento definido en la Práctica 1. Podéis modificarlo como creáis conveniente, ya que a la hora de trabajar con los modelos podéis seguir descubriendo información de las variables. 

Es fundamental encapsular todas las transformaciones (imputación, escalado, codificación, ingeniería de características) desarrolladas previamente en un único `Pipeline` o `ColumnTransformer` para aplicarlo consistentemente antes de cada modelo.

*Recordatorio: Asegúrate de que tu pipeline de preprocesamiento maneja adecuadamente todos los tipos de variables y artefactos presentes en los datos (`numéricas`, `categóricas`, `fechas`, `texto`, `valores faltantes`, etc.)*.

## 2.1 Pipeline de la practica anterior
En esta parte está copiado el código que implementa la pipeline, realizada en la practica 1. Si en algún momento le hago alguna modificación, lo pondré en otro apartado.

### Importaciones

In [23]:
import pandas as pd
import numpy as np
import re
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

import time

### Separación del Dataframe

In [24]:
y=df_train['abandono']
X=df_train.drop(columns=['abandono'])

### Clasificación de variables

In [25]:
# Numéricas genéricas
numericas=[
    'nota_acceso', 'creditos_a1', 'superados_a1', 'nota_s1', 'satisfaccion',
    'posts_foro', 'uso_biblioteca', 'eventos', 'tutorias',
    'meses_matriculado', 'talla_zapato', 'horas_trabajo'
]

# Categóricas genéricas
categoricas=[
    'trabaja', 'modalidad', 'comentarios'
]

# Variables que necesitan una transformación específica
fecha =['nacimiento']
moodle = ['horas_moodle']
provincia = ['provincia']
bachillerato = ['bachillerato']

### Transformadores específicos

In [26]:
# Transformador para nacimento
class TransformadorNacimiento(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None): return self
    def transform(self, X, y=None):
        X_dt = pd.to_datetime(X.iloc[:, 0], format='%Y-%m-%d', errors='coerce')
        return X_dt.apply(lambda fecha: fecha.year if pd.notna(fecha) else np.nan).to_frame()
    
# Transformador para horas_moodle
class TransformadorHorasMoodle(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None): return self
    def transform(self, X, y=None):
        def limpiar_horas_moodle(valor):
            match = re.search(r'[\d\.]+', str(valor))
            return float(match.group(0)) if match else np.nan
        return X.iloc[:, 0].apply(limpiar_horas_moodle).to_frame()
    
# Transformador para provincia
class TransformadorProvincia(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None): return self
    def transform(self, X, y=None):
        provincias_principales = {'Albacete', 'Cuenca', 'Ciudad Real', 'Toledo'}
        def limpiar_provincia(prov):
            return prov if prov in provincias_principales else 'Otro'
        return X.iloc[:, 0].astype(str).apply(limpiar_provincia).to_frame()
    
# Transformador para bachillerato
class TransformadorBachillerato(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None): return self
    def transform(self, X, y=None):
        diccionario = {
            'científico': 'ciencias', 'ciencias puras': 'ciencias',
            'cientifico-tecnologico': 'tecnologico', 'tecnológico': 'tecnologico',
            'tecnológico industrial': 'tecnologico', 'letras': 'humanidades',
            'económico': 'ciencias sociales', 'ccss': 'ciencias sociales',
            'ciencias': 'ciencias', 'humanidades': 'humanidades',
            'ciencias sociales': 'ciencias sociales', 'artes': 'artes'
        }
        serie = X.iloc[:, 0].astype(str).str.lower().str.strip().replace(diccionario)
        return serie.fillna('missing').to_frame()

### Pipelines de Transformación

In [27]:
transformador_numerico = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

transformador_categorico = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

transformador_moodle = Pipeline(steps=[
    ('cleaner', TransformadorHorasMoodle()),
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

transformador_provincia = Pipeline(steps=[
    ('grouper', TransformadorProvincia()),
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

transformador_bachillerato = Pipeline(steps=[
    ('mapper', TransformadorBachillerato()),
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

transformador_nacimiento = Pipeline(steps=[
    ('date_to_year', TransformadorNacimiento()),
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

### Column Transformer

In [28]:
preprocesador = ColumnTransformer(
    transformers=[
        ('moodle_pipe', transformador_moodle, moodle),
        ('date_pipe', transformador_nacimiento, fecha),
        ('prov_pipe', transformador_provincia, provincia),
        ('bach_pipe', transformador_bachillerato, bachillerato),
        ('num_pipe', transformador_numerico, numericas),
        ('cat_pipe', transformador_categorico, categoricas),
    ],
    remainder='drop' # Con esta linea, elimino todas las variables que no he transformado (id, nombre, residencia_id, numero_fav, color_fav y grupo_trabajo)
)

## **<font color="#B30033" size=10>Trabajo Realizado </font>**

## 1. Preparación de los modelos a usar

En esta parte voy a cargar, a crear su pipeline y probar los diferentes modelos que tengo que probar en esta práctica.

In [29]:
# imports de modelos normales
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

#imports de modelos ensembles
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import HistGradientBoostingClassifier

# import y definición de la estrategia de la validacion
from sklearn.model_selection import RepeatedStratifiedKFold
cv_strategy= RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=5,
    random_state=semilla
)

## 1.1 Modelos convencionales

### KNeighbors

In [32]:
knn= KNeighborsClassifier()

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',knn)])

start_time=time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Vecinos Más cercanos\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), 'Tiempo de ejecucion : ', time.time()-start_time)

Vecinos Más cercanos
Media :  0.5634880336953931
Desviación estandar :  0.005760624209641265 Tiempo de ejecucion :  61.01561903953552

### Naive Bayes Gaussiano

In [ ]:
gaussianNB= GaussianNB()

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',gaussianNB)])

start_time=time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Naive bayes gaussiano\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución : ', time.time()-start_time)

Naive bayes gaussiano
Media :  0.5591069704025773
Desviación estandar :  0.005105154521772015
Tiempo de ejecución : 4.9327452182769775

### Árbol de Decisión

In [40]:
arbol= DecisionTreeClassifier(random_state=semilla)

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',arbol)])

start_time = time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Arbol de decisiones\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Arbol de decisiones
Media :  0.6350464228500803
Desviación estandar :  0.007337569787926078
Tiempo de ejecución : 34.712008237838745

Exception ignored in: <function ResourceTracker.__del__ at 0x7ec6902aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a6585eaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77ebbbfae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75b1eb9a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d78dd7aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x72b2d78aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e9725ca2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7df0f4bae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73cee678e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a1ed8f9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x745669ea2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71e5d9dae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7317ede9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x72aaf3daa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x787965da2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7edc496a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d76a31a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a1ad62aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a6172f9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ebbf258e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73bbb0d8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77a2842a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73ca32aa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73dd11baa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

## 1.2 Modelos ensemble

### Bagging

In [34]:
bagging=BaggingClassifier(random_state=semilla)

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',bagging)])

start_time = time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Bagging\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Bagging
Media :  0.6435682387266659
Desviación estandar :  0.006781108508825453
Tiempo de ejecución : 161.2373731136322

### Random Forest

In [35]:
forest=RandomForestClassifier(random_state=semilla)

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',forest)])

start_time = time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Random Forest\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Random Forest
Media :  0.6515361127866188
Desviación estandar :  0.005614942332650061
Tiempo de ejecución : 102.18804216384888

### Adaptive Boosting

In [36]:
adaBoost=AdaBoostClassifier(random_state=semilla)

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',adaBoost)])

start_time = time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Adaptive Boosting\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Adaptive Boosting
Media :  0.516461733705637
Desviación estandar :  0.025818660062118946
Tiempo de ejecución : 80.30487489700317

### Gradient Tree Boosting

In [37]:
gradientTree=GradientBoostingClassifier(random_state=semilla)

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',gradientTree)])

start_time = time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Gradient Tree Boosting\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Gradient Tree Boosting
Media :  0.6308721192439692
Desviación estandar :  0.0046388385940072385
Tiempo de ejecución : 304.0388116836548

### Histogram-Based Gradient Boosting

In [ ]:
histGradient=HistGradientBoostingClassifier(random_state=semilla)

pipeline=Pipeline([
    ('preprocessor',preprocesador),
    ('classifier',histGradient)])

start_time = time.time()
scores=cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Histagram-Based Gradient Boosting\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Histagram-Based Gradient Boosting
Media :  0.7059639963509449
Desviación estandar :  0.005393269833206044
Tiempo de ejecución : 69.9922890663147

Exception ignored in: <function ResourceTracker.__del__ at 0x79f76b69e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b3a64dae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7203cd7a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f4d13da6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x783d4c1ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x757d466aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7807095aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d743478e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f8bce58e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x741237aaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f92f53a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7235073a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x789b7aba6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7fcbc9f8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7da5c729e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7486929ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x711a32fae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x700f7798e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c59d759e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73a34eaaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x724db97aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7102a07a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7728d49ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7cc2fffaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

### Stacking Classifier

Este es el modelo que he elegido implementar e investigar por mi cuenta, ya que me parece muy interesante como funciona. La forma de funcioanmiento de este modeleo, se basa en dos capas: la primera es un conjunto de modelos básicos diversos, como por ejemplo Regresión logistica o un Árbol de decisiones, los cuales son entrenados y generan sus propias prediciones; y la segunda capa es un modelo que se entrena para predecir cual es la predicción final, este modelo no trata directamente con el conjunto de entrenamiento ni nada del dataset, sino que solo 've' las predicciones generadas por la primera capa.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier

# Modelos que utilizará la capa 1 para generar las predicciones
estimators_base = [
    # 1. Modelo Lineal
    ('log_reg', LogisticRegression(random_state=semilla, solver='liblinear', max_iter=1000)), 
    # 2. Modelo Basado en Árboles
    ('dt', DecisionTreeClassifier(random_state=semilla)), 
]

stacking_model = StackingClassifier(
    estimators=estimators_base, 
    final_estimator=LogisticRegression(random_state=semilla, solver='liblinear'), 
    n_jobs=-1,
    passthrough=False 
)

pipeline = Pipeline([
    ('preprocessor', preprocesador),
    ('classifier', stacking_model)
])

start_time = time.time()
scores = cross_val_score(
    estimator=pipeline,
    X=X,
    y=y,
    cv=cv_strategy,
    scoring='f1_macro',
    n_jobs=-1
)

print('Stacking Classifier\nMedia : ', np.mean(scores), '\nDesviación estandar : ', np.std(scores), '\nTiempo de ejecución :', time.time()-start_time)

Stacking Classifier
Media :  0.7716656182717574
Desviación estandar :  0.005343187265631992
Tiempo de ejecución : 161.1334626674652

Exception ignored in: <function ResourceTracker.__del__ at 0x74b4bcaaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x783ca7caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f8007b9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79adbad9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b2442b8a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x768b369aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a0f858aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ed4b7ca2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ea8231aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7cba1d6aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7639c1aaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7db63d19a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x726aea9a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76ae6b49e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d16a549e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x713dbeba6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x74d699caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76f859ba2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c4179d9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7957df9ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79bed90aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x767f2e0aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71ad51ba6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

De estas breves pruebas lo que puedo sacar en claro es que de normal, los modelos ensemble suelen obtener un mejor resultado que los modelos convencionales (especialmente Histagram-Based Gradient Boosting y StackingClassifier), aunque también tardan un tiempo considerablemente superior en ejecutarse.

## 2. Selección de Hiperparámetros

En esta parte, voy a probar los modelos anteriores, variando los hiperparámetros, para ver cuál es la mejor configuración para cada modelo. Además obtendré un muy buen resulyado de score para cada uno de los modelos, por lo que luego me permitirá escoger mejor al indicado. Para ello haré uso de la función facilitada en el cuaderno de ejemplo de esta misma práctica, 'optimize_with_grid_search'.

### Función facilitada

In [41]:
from sklearn.model_selection import GridSearchCV

def optimize_with_grid_search(estimator, param_grid, X_train, y_train, cv_strategy, scoring_metric='accuracy', refit=True):
    n_jobs = -1  # Usar todos los cores de CPU disponibles
    return_train_score = True # Incluir puntuaciones de entrenamiento en los resultados

    grid_search = GridSearchCV(
        estimator=estimator,
        param_grid=param_grid,
        scoring=scoring_metric,
        n_jobs=n_jobs,
        cv=cv_strategy,
        refit=refit, # Pasa refit directamente como se configuró
        return_train_score=return_train_score,
        verbose=1 # Muestra actualizaciones de progreso
    )

    model_name = type(estimator).__name__
    if isinstance(estimator, Pipeline):
        # Obtener el nombre del último paso (clasificador) si es un pipeline
        model_name = type(estimator.steps[-1][1]).__name__

    print(f"--- Iniciando GridSearchCV para {model_name} ---")
    start_time = time.time()
    grid_search.fit(X_train, y_train)
    end_time = time.time()
    print(f"GridSearchCV para {model_name} completado en {end_time - start_time:.2f} segundos.")

    # --- Procesar y Mostrar Resultados ---
    print(f"\nMejores Parámetros encontrados para {model_name}:")
    print(grid_search.best_params_)
    refit_metric_key = refit if isinstance(refit, str) else next(iter(grid_search.scoring)) if isinstance(grid_search.scoring, dict) else 'score'
    print(f"\nMejor Puntuación Media CV ({refit_metric_key}): {grid_search.best_score_:.4f}")

    results_df = pd.DataFrame(grid_search.cv_results_)
    rank_col_name = f"rank_test_{refit_metric_key}"

    # Ordenar por la columna de ranking
    if rank_col_name in results_df.columns:
        results_df = results_df.sort_values(by=rank_col_name)

    # Seleccionar columnas relevantes para mostrar
    param_cols = [col for col in results_df.columns if col.startswith('param_')]
    score_cols = [col for col in results_df.columns if ('mean_test_' in col or 'std_test_' in col or col.startswith('rank_test_'))]
    train_score_cols = [col for col in results_df.columns if ('mean_train_' in col or 'std_train_' in col)]
    time_cols = ['mean_fit_time', 'std_fit_time', 'mean_score_time', 'std_score_time']

    # Asegurar que todas las columnas seleccionadas existen
    cols_to_display = param_cols + [col for col in score_cols if col in results_df.columns] + \
                      [col for col in train_score_cols if col in results_df.columns] + \
                      [col for col in time_cols if col in results_df.columns]
    # Eliminar duplicados si alguna columna aparece en múltiples listas
    cols_to_display = sorted(list(set(cols_to_display)), key=lambda x: (not x.startswith('param_'), x))

    print(f"\nResumen de Resultados GridSearchCV para {model_name}:")
    display(results_df[cols_to_display])
    return grid_search

## 2.1 Selección de Hiperparámetros de modelos convencionales

### KNeighbors

In [ ]:
knn_pipeline = Pipeline([('preprocessor', preprocesador), ('knn', KNeighborsClassifier())])

knn_param_grid = {
    'knn__n_neighbors': [1, 3, 5, 7, 9],
    'knn__weights': ['uniform', 'distance'],
    'knn__metric': ['euclidean', 'manhattan', 'minkowski'],
    'preprocessing__column_transformer__num__imputer__strategy': ['mean', 'median']
}

knn_search_results = optimize_with_grid_search(
    estimator=knn_pipeline,
    param_grid=knn_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro',
    refit=True
)

mejor_knn = knn_search_results.best_estimator_

No he podido ejecutar este modelo, ya que me da un error que no he podido resolver de ningún modo. Por lo que parece el error que me da es de alguna parte del proceso del ColumnTransformer.

### Naive Bayes Gaussiano

In [ ]:
nb_pipeline = Pipeline([('preprocessor', preprocesador), ('nb', GaussianNB())])

nb_param_grid = {
    'nb__var_smoothing': np.logspace(-9, 0, num=30)
}

nb_search_results = optimize_with_grid_search(
    estimator=nb_pipeline,
    param_grid=nb_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro',
    refit=True
)

mejor_nb = nb_search_results.best_estimator_

--- Iniciando GridSearchCV para GaussianNB ---
Fitting 25 folds for each of 30 candidates, totalling 750 fits
GridSearchCV para GaussianNB completado en 173.73 segundos.

Mejores Parámetros encontrados para GaussianNB:
{'nb__var_smoothing': np.float64(0.006723357536499335)}

Mejor Puntuación Media CV (score): 0.7549

Resumen de Resultados GridSearchCV para GaussianNB:

,param_nb__var_smoothing,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
22,6.723358e-03,2.059661,0.580634,0.754880,0.763449,1,0.273608,0.102403,0.005042,0.001227
21,3.290345e-03,2.192706,0.588402,0.740768,0.753986,2,0.269321,0.116298,0.005675,0.001962
23,1.373824e-02,2.109313,0.564135,0.731241,0.737910,3,0.267768,0.112868,0.005571,0.001446
20,1.610262e-03,2.107687,0.561823,0.730909,0.746182,4,0.267074,0.093281,0.005329,0.002082
19,7.880463e-04,2.191947,0.556562,0.726055,0.741865,5,0.337039,0.105673,0.005451,0.001683
18,3.856620e-04,2.103742,0.582799,0.722914,0.738783,6,0.286420,0.108892,0.005968,0.001588
16,9.236709e-05,2.228907,0.599402,0.721808,0.736351,7,0.300897,0.109202,0.006222,0.001530
17,1.887392e-04,2.070939,0.565533,0.721733,0.736813,8,0.289300,0.096413,0.005999,0.001705
15,4.520354e-05,1.985158,0.567144,0.721375,0.735810,9,0.308559,0.112657,0.006063,0.001738
14,2.212216e-05,2.078523,0.569270,0.721080,0.735647,10,0.310812,0.123208,0.006132,0.001641
13,1.082637e-05,2.171303,0.567423,0.720387,0.736023,11,0.283760,0.111972,0.005959,0.001608
12,5.298317e-06,2.182570,0.597451,0.720184,0.736240,12,0.311287,0.134020,0.006512,0.002386
11,2.592944e-06,2.200650,0.593482,0.687679,0.702642,13,0.281648,0.156798,0.044018,0.044150
24,2.807216e-02,2.134563,0.578351,0.665807,0.669024,14,0.283836,0.092003,0.005222,0.001430
10,1.268961e-06,2.141562,0.582301,0.644541,0.657721,15,0.268427,0.109396,0.054160,0.055017
25,5.736153e-02,2.181286,0.554822,0.611113,0.612633,16,0.218476,0.095081,0.004813,0.001031
9,6.210169e-07,2.056824,0.595824,0.609819,0.622559,17,0.378996,0.102385,0.035409,0.035863
8,3.039195e-07,2.044441,0.534131,0.589956,0.601852,18,0.290662,0.110982,0.014870,0.013985
26,1.172102e-01,2.053687,0.547973,0.588731,0.589521,19,0.235754,0.118219,0.004111,0.000970
7,1.487352e-07,2.090974,0.572270,0.581397,0.592541,20,0.313900,0.105589,0.011671,0.011774
27,2.395027e-01,2.061500,0.541880,0.576894,0.577426,21,0.285200,0.111930,0.003777,0.001150
6,7.278954e-08,2.209605,0.601396,0.575169,0.585998,22,0.262733,0.107432,0.009223,0.009678
5,3.562248e-08,2.113286,0.560917,0.570653,0.580767,23,0.324839,0.102371,0.008144,0.008472
4,1.743329e-08,2.230837,0.595853,0.566932,0.576579,24,0.261234,0.120099,0.006199,0.006544
3,8.531679e-09,2.159756,0.567651,0.564521,0.573947,25,0.238408,0.126473,0.005466,0.005832
2,4.175319e-09,2.147348,0.575045,0.562728,0.571687,26,0.274434,0.121267,0.005705,0.006377
1,2.043360e-09,2.196020,0.604487,0.560973,0.569781,27,0.257681,0.120586,0.005435,0.006135
0,1.000000e-09,2.080302,0.596774,0.559107,0.567529,28,0.385257,0.154626,0.005105,0.005574
28,4.893901e-01,2.079373,0.597706,0.558466,0.558774,29,0.260017,0.100879,0.003985,0.001328
29,1.000000e+00,2.107858,0.530488,0.528444,0.528836,30,0.250870,0.141604,0.004153,0.001424

Exception ignored in: <function ResourceTracker.__del__ at 0x70662fb8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7504a15a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7462fc9a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d1d366aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x735fb6ea2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x708e757a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c5a7769e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x765c3d8aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7fc6dc4aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7092623ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75648018a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7450963a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f81429ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77a8548a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75011e2aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77e596d8a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7205389b2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b7b6b18e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78ffca8aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71af2f7a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7eae413b2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7df7abdaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78fd1129e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78328c9a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

Para el modelo de Naive Bayes Gaussiano, el hiperparámetro que he modificado es la 'varianza artificial' que se le añade a cada característica durante el entrenamiento del modelo. En concreto los valores que he probado son 30 valores diferentes entre 10⁻9 y 1. Cuanto más próximo a 0 es esta varianza más similar será su comportamiento a un modelo Naive Bayes convencional, y cuanto mayor sea esa varianza (más próxima a 1), el modelo se suaviza, y actua en parte como si estuvuera regularizado. Como se puede ver, el mejor valor tanto para train y test, se consigue con un valor de varianza artificial que se encuantra a medio camino, aunque más próximo al 1; lo que nos prodría indicar que el modelo de Naive Bayes para este conjunto de datos, necesita algún tipo de suavizado, aunque no mucho. Esto último se refuerza viendo que los peores resultados se han conseguido con un valor muy cercano a 1 o a 0.

### Árbol de decisiones

In [50]:
arbol_pipeline = Pipeline([
    ('preprocessor', preprocesador),
    ('classifier', DecisionTreeClassifier(random_state=semilla)) 
])

arbol_param_grid = {
    'classifier__max_depth': [10, 20, 30, None], # Profundidad máxima (None significa ilimitada)
    'classifier__min_samples_split': [2, 5, 10], # Mínimo de muestras para dividir un nodo
    'classifier__min_samples_leaf': [1, 5, 10], # Mínimo de muestras que debe tener un nodo hoja
    'classifier__criterion': ['gini', 'entropy'] # Función para medir la calidad de la división
}

arbol_grid_search = optimize_with_grid_search(
    estimator=arbol_pipeline,
    param_grid=arbol_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro'
)

mejor_arbol=arbol_grid_search.best_estimator_

--- Iniciando GridSearchCV para DecisionTreeClassifier ---
Fitting 25 folds for each of 72 candidates, totalling 1800 fits
GridSearchCV para DecisionTreeClassifier completado en 878.89 segundos.

Mejores Parámetros encontrados para DecisionTreeClassifier:
{'classifier__criterion': 'gini', 'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 10}

Mejor Puntuación Media CV (score): 0.6423

Resumen de Resultados GridSearchCV para DecisionTreeClassifier:

,param_classifier__criterion,param_classifier__max_depth,param_classifier__min_samples_leaf,param_classifier__min_samples_split,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
29,gini,None,1,10,20.955236,0.464049,0.642293,0.926228,1,1.586234,0.074924,0.007021,0.001915
28,gini,None,1,5,20.851591,0.467261,0.639080,0.968535,2,1.259533,0.070222,0.006492,0.001046
27,gini,None,1,2,20.954926,0.460796,0.635046,1.000000,3,1.159359,0.064717,0.007338,0.000000
20,gini,30,1,10,12.009090,0.500645,0.634181,0.807014,4,0.851767,0.102348,0.006171,0.008753
18,gini,30,1,2,12.105555,0.470785,0.634063,0.839589,5,0.691197,0.070264,0.006134,0.010714
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,entropy,10,5,5,6.285298,0.440937,0.575676,0.602785,67,0.397590,0.075044,0.014004,0.012050
41,entropy,10,5,10,6.060465,0.448866,0.575676,0.602785,67,0.385491,0.061798,0.014004,0.012050
43,entropy,10,10,5,5.698536,0.433560,0.573407,0.599265,70,0.346513,0.072218,0.010226,0.009616
44,entropy,10,10,10,5.741739,0.448412,0.573407,0.599265,70,0.336561,0.059201,0.010226,0.009616
42,entropy,10,10,2,5.968394,0.446968,0.573407,0.599265,70,0.355456,0.068730,0.010226,0.009616

Exception ignored in: <function ResourceTracker.__del__ at 0x7d2ec87a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7007a6bae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7945f60aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b48e81ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a35b9a9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76ec324aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x74559c9ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7666f02a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7480daaa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77206f8aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x707b586aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x734807aaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7868ecc9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70017f38a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f19d95aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x744dbf89e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x703bac18e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x744e066a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76d5563aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7aa0c5caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76be460aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x702342d9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7329500aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7902a0d8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

En cuanto al árbol de decisiones, el hiperparámetro más relevante parece ser el criterio, ya que como se puede ver, todos los buenos resultados mostrados en la tabla, se han obtenido con 'gini' como criterio y todos los malos con 'entropy'.  
  

Otro que parece muy relevante es la profundidad, ya que se ve como los mejores resultados se han conseguido o sin limite o con limite = 30 (el mayor valor con el que e probado); mientras que los peores resultados se han conseguido con limite = 10 (el mínimo valor que he probado), por lo que la conclusión que se puede sacar es que para este conjunto de datos es mejor un límite de profundidad muy grande o no tener limite directamente.  
  
Algo similar pasa con el mínimo de muestras de cada nodo hoja, aunque al revés, es decir que por lo que se ve en los resultados, los mejores scores se han obtenido con el número mínimo posible para ese hiperparámetro, mientras que los peores se han obtenido con minimo de muestras más grandes, por lo que se puede asumir que para este conjunto de datos es mejor pocas muestras por hoja.  
  
El último hiperparámetro, el número mínimo de muestras que debe de terner un nodo para poder dividirlo, es el que parece más inutil, ya que los 3 mejores scores (y los 3 peores) se han obtenido con la misma convinación de los 3 anteriores hiperparámetros, solo cambiando este. Además se puede ver, especialmente en los mejores scores como un número bajo de este hiperparámetro hace que haya mucho overfittin, llegando el tercer modelo a tener un 1 en el train.

## 2.2 Selección de Hiperparámetros de modelos ensemble

### Bagging

In [ ]:
bagging_pipeline = Pipeline([
    ('preprocessor', preprocesador),
    ('bagging', BaggingClassifier(
        estimator=DecisionTreeClassifier(random_state=semilla),
        random_state=semilla
    ))
])

bagging_param_grid = {
    'bagging__n_estimators': [20, 50, 100], 
    'bagging__estimator__max_depth': [3, 5, 10, None], 
    'bagging__estimator__min_samples_leaf': [1, 5, 20] 
}

bagging_search_results = optimize_with_grid_search(
    estimator=bagging_pipeline,
    param_grid=bagging_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro',
    refit=True
)

best_bagging_model = bagging_search_results.best_estimator_

--- Iniciando GridSearchCV para BaggingClassifier ---
Fitting 25 folds for each of 36 candidates, totalling 900 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x7e1e16ca2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7db763baa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7245f35aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a393b5aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e26e8dae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7aa7a8e9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7927a0a9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x718a70caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7066f6baa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73c7356a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78c3e9aaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70b9237aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77c03ada2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73acecea2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7599699aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x746f0e89e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b4b034aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e0b33d8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ac05aaaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x775a0eb9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a7cbd2aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70347549e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71c826fa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73cdc5bae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

GridSearchCV para BaggingClassifier completado en 10404.09 segundos.

Mejores Parámetros encontrados para BaggingClassifier:
{'bagging__estimator__max_depth': None, 'bagging__estimator__min_samples_leaf': 1, 'bagging__n_estimators': 100}

Mejor Puntuación Media CV (score): 0.6539

Resumen de Resultados GridSearchCV para BaggingClassifier:

,param_bagging__estimator__max_depth,param_bagging__estimator__min_samples_leaf,param_bagging__n_estimators,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
29,None,1,100,1179.714351,11.406584,0.653894,0.999948,1,55.561919,1.317958,0.006134,0.000048
28,None,1,50,599.549595,5.704940,0.652788,0.998992,2,26.886686,0.776528,0.005986,0.000229
27,None,1,20,255.387522,2.437713,0.648070,0.990604,3,17.173122,0.450152,0.006459,0.000518
30,None,5,20,128.490322,2.185428,0.616431,0.857848,4,6.564886,0.329124,0.006760,0.001860
31,None,5,50,318.551614,5.395271,0.614230,0.861846,5,12.877847,0.740213,0.006922,0.002343
32,None,5,100,590.188677,10.070216,0.612951,0.864138,6,23.994581,1.482002,0.006112,0.001773
18,10,1,20,87.987911,2.914935,0.575207,0.621144,7,3.291904,0.286400,0.005540,0.003972
21,10,5,20,84.099434,2.827313,0.574834,0.615930,8,3.358507,0.406313,0.005513,0.004088
33,None,20,20,73.390591,2.376963,0.574263,0.633315,9,2.466803,0.359908,0.004826,0.002681
19,10,1,50,210.666345,6.377752,0.572846,0.620919,10,10.657420,0.640012,0.005950,0.004122
22,10,5,50,207.739329,6.424456,0.572324,0.614898,11,10.042383,0.713277,0.006008,0.004158
20,10,1,100,412.018068,12.503987,0.572020,0.620311,12,27.465053,1.571055,0.005421,0.004138
23,10,5,100,384.499264,11.810006,0.571077,0.614156,13,12.665884,1.826678,0.005183,0.004147
34,None,20,50,177.392018,5.069420,0.570382,0.627364,14,5.113692,0.774398,0.004279,0.003096
35,None,20,100,327.858097,6.659513,0.569798,0.625837,15,41.094139,2.341758,0.004572,0.003488
24,10,20,20,70.373277,2.602525,0.564880,0.592563,16,3.183227,0.600082,0.005001,0.003847
25,10,20,50,169.090134,5.540170,0.563384,0.591232,17,9.062336,0.920995,0.004772,0.003027
26,10,20,100,332.628548,11.566511,0.562728,0.590616,18,12.243569,1.912505,0.004930,0.003341
9,5,1,20,56.698127,3.021418,0.536996,0.540435,19,2.244788,0.357268,0.006727,0.002854
12,5,5,20,54.734865,2.819967,0.536976,0.540186,20,3.867797,0.374748,0.006471,0.002735
10,5,1,50,133.094263,6.990684,0.536789,0.540158,21,3.794832,0.735664,0.005520,0.001918
13,5,5,50,129.207521,6.692997,0.536677,0.539882,22,6.615826,0.702501,0.005540,0.001765
11,5,1,100,262.076112,13.262897,0.536269,0.539524,23,8.817606,1.682495,0.005701,0.001967
14,5,5,100,240.587776,12.332501,0.536113,0.539364,24,14.397983,1.594890,0.005768,0.001910
15,5,20,20,55.241521,2.995007,0.535763,0.537735,25,2.833769,0.426110,0.006247,0.003544
16,5,20,50,129.476694,6.718778,0.535063,0.537167,26,9.970697,0.746998,0.006028,0.002536
17,5,20,100,254.433686,13.143561,0.534625,0.536810,27,7.634296,1.482116,0.005905,0.002783
2,3,1,100,166.269656,13.076348,0.530537,0.530998,28,7.898506,1.097962,0.004749,0.003403
5,3,5,100,177.700811,13.890692,0.530537,0.530998,28,5.521948,1.182149,0.004749,0.003403
8,3,20,100,179.533638,13.930629,0.530406,0.530691,30,7.117161,0.992378,0.004746,0.003492
4,3,5,50,89.015628,6.842285,0.530249,0.530668,31,3.259762,0.664436,0.005031,0.003544
1,3,1,50,78.168290,5.826799,0.530249,0.530668,31,6.670498,0.739787,0.005031,0.003544
0,3,1,20,30.977538,2.657180,0.530209,0.530643,33,1.373949,0.431841,0.004976,0.003455
3,3,5,20,37.237605,3.086203,0.530209,0.530643,33,2.429761,0.359955,0.004976,0.003455
7,3,20,50,90.024207,6.810786,0.530084,0.530339,35,3.786487,0.632382,0.005050,0.003793
6,3,20,20,37.520439,3.109129,0.530040,0.530295,36,2.432134,0.324263,0.005068,0.003890

Al igual que pasaba en el árbol de decisiones, parece que el hiperparámetro profundidad máxima es muy relevante, siendo cuanto mayor alta mejor de normal, y cuanto menor es el límite mucho menor score obtiene. Esto tiene sentido, ya que al fin y al cabo este modelo utiliza árboles de decisiones.  
  
Lo mismo pasa con el mínimo de muestras por hoja, aunque de una maner un poco diferente, ya que aqui si que vemos que hay ocasiones en las que es mejor tener un limite de muestras diferente del mínimo, cosa que en el aŕbol no pasaba.  
  
El hiperparámetro que parece ser más irrelevante es el número de modelos, lo cual parece indicar que al menos para este conjunto de datos es más importante que los modelos sean lo mejor posibles cada uno de ellos, a que haya muchos. Si que es cierto que paar árboles iguales (los otros dos hiperparámetros constantes) si que es mejor que hay más modelos, aunque no siempre.

### Random Forest

In [ ]:
rf_pipeline = Pipeline([
    ('preprocessor', preprocesador),
    ('random_forest', RandomForestClassifier(random_state=semilla, n_jobs=-1))
])

rf_param_grid = {
    'random_forest__n_estimators': [50, 100, 200], 
    'random_forest__max_depth': [5, 10, None], 
    'random_forest__min_samples_leaf': [1, 5, 10] 
}

rf_grid_search = optimize_with_grid_search(
    estimator=rf_pipeline,
    param_grid=rf_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro'
)

mejor_forest=rf_grid_search.best_estimator_

--- Iniciando GridSearchCV para RandomForestClassifier ---
Fitting 25 folds for each of 27 candidates, totalling 675 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x722b1c2aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
/var/data/python/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
Exception ignored in: <function ResourceTracker.__del__ at 0x7d4fc589e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7364715ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79198da9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x719ddb8aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f2f701a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e902f7a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ff7ac0aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70f1487aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ca077f9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7eab52aa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ae3339aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x74ceab6a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79f3ecfae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7090cc0aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x788c90f8a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7883a8da2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76fb494aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70299afa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a0ebfeaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d5375eaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79232adae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x72100db9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7609e8fb2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

GridSearchCV para RandomForestClassifier completado en 1091.64 segundos.

Mejores Parámetros encontrados para RandomForestClassifier:
{'random_forest__max_depth': None, 'random_forest__min_samples_leaf': 1, 'random_forest__n_estimators': 200}

Mejor Puntuación Media CV (score): 0.6534

Resumen de Resultados GridSearchCV para RandomForestClassifier:

,param_random_forest__max_depth,param_random_forest__min_samples_leaf,param_random_forest__n_estimators,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
20,None,1,200,125.347982,6.588592,0.653360,1.000000,1,27.909081,4.357145,0.005483,0.000000
19,None,1,100,58.462572,5.554850,0.651536,0.999984,2,9.050444,2.688145,0.005615,0.000023
18,None,1,50,24.178534,3.210976,0.649284,0.999462,3,4.688601,1.241046,0.006014,0.000110
21,None,5,50,9.608857,2.385358,0.569972,0.593083,4,4.926437,1.713090,0.006461,0.006097
23,None,5,200,66.398235,7.300328,0.567882,0.591609,5,13.832850,3.225115,0.005931,0.005217
22,None,5,100,27.195261,5.100984,0.567820,0.591644,6,10.199281,2.469274,0.005833,0.005083
24,None,10,50,14.957194,2.333323,0.510602,0.520868,7,7.692699,1.076268,0.008453,0.008637
25,None,10,100,21.362322,4.116251,0.508299,0.518188,8,6.460306,1.711083,0.006651,0.006466
26,None,10,200,51.990435,6.250123,0.503695,0.514589,9,10.912186,2.832948,0.005967,0.004568
9,10,1,50,7.003928,1.539620,0.463442,0.471641,10,1.757125,0.640720,0.008299,0.007817
10,10,1,100,10.876698,2.288902,0.457769,0.464842,11,2.259004,0.743968,0.006516,0.006179
12,10,5,50,9.230659,2.198696,0.457474,0.461149,12,3.904226,1.744182,0.009030,0.008441
11,10,1,200,28.145539,4.088082,0.453240,0.459934,13,5.898259,1.778055,0.004826,0.003459
13,10,5,100,15.275711,3.243291,0.451285,0.454712,14,4.616348,1.854910,0.006102,0.004994
15,10,10,50,8.713398,1.983914,0.447805,0.449694,15,3.069271,1.416985,0.006587,0.006355
14,10,5,200,26.016021,3.387505,0.445313,0.448676,16,5.510159,1.413202,0.004135,0.003046
16,10,10,100,11.263696,2.647359,0.442729,0.445254,17,2.852818,1.366375,0.005249,0.004111
17,10,10,200,27.179766,5.204839,0.438723,0.440271,18,5.181863,1.641279,0.003842,0.002645
3,5,5,50,4.698501,1.165735,0.426212,0.426238,19,1.874472,0.706891,0.000451,0.000279
0,5,1,50,4.131785,1.104069,0.426192,0.426212,20,0.704782,0.397366,0.000343,0.000176
6,5,10,50,5.436996,1.061753,0.426172,0.426126,21,2.118046,0.511655,0.000366,0.000147
7,5,10,100,6.837549,1.669074,0.426111,0.426045,22,1.148794,0.711245,0.000196,0.000057
1,5,1,100,7.948010,1.845682,0.426070,0.426131,23,1.825740,0.597770,0.000165,0.000110
4,5,5,100,6.649633,1.635294,0.426050,0.426111,24,1.373627,0.941554,0.000134,0.000088
5,5,5,200,13.786056,2.639059,0.426050,0.426045,24,2.845148,1.240943,0.000134,0.000057
2,5,1,200,14.684501,2.352541,0.426050,0.426065,24,3.024799,0.937034,0.000134,0.000064
8,5,10,200,16.157524,3.332091,0.426009,0.426024,27,4.257590,1.792948,0.000020,0.000042

Exception ignored in: <function ResourceTracker.__del__ at 0x7fe669d8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x726c843a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79922daa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7cf0370aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b0c29eaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ef3fed8a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x728247f8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78aa295aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x79d2f658e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76a6105aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7efa7db8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x74bea48aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x791a143a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71b5fdaa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c765a6a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7add7f39a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70c921fa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7340619ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77c65a58e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a792daaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f7b372aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7344187a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7895d71a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76f55c3a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

Este modelo básicamente presenta las mismas características que el anterior (ya que también funciona con árboles de decisión y tienen los mismos hiperparámetros) pero mucho más pronunciadas, sobre todo se puede ver en la profundidad máxima.

### Adaptive boost

In [51]:
adaptive_boost_pipeline = Pipeline([
    ('preprocessor', preprocesador),
    ('adaboost', AdaBoostClassifier(random_state=semilla, estimator=DecisionTreeClassifier(max_depth=1))) 
])

adaptive_boost_param_grid = {
    'adaboost__n_estimators': [50, 100, 200, 300],
    'adaboost__learning_rate': [0.01, 0.1, 0.5, 1.0], 
}

adaptive_boost_grid_search = optimize_with_grid_search(
    estimator=adaptive_boost_pipeline,
    param_grid=adaptive_boost_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro'
)

mejor_adaboost=adaptive_boost_grid_search.best_estimator_

--- Iniciando GridSearchCV para AdaBoostClassifier ---
Fitting 25 folds for each of 16 candidates, totalling 400 fits
GridSearchCV para AdaBoostClassifier completado en 4235.09 segundos.

Mejores Parámetros encontrados para AdaBoostClassifier:
{'adaboost__learning_rate': 1.0, 'adaboost__n_estimators': 300}

Mejor Puntuación Media CV (score): 0.5477

Resumen de Resultados GridSearchCV para AdaBoostClassifier:

,param_adaboost__learning_rate,param_adaboost__n_estimators,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
15,1.00,300,360.742557,9.106441,0.547728,0.550585,1,55.967222,3.630330,0.009691,0.010281
14,1.00,200,257.851902,8.215490,0.541546,0.544339,2,8.394111,0.863147,0.010990,0.011328
13,1.00,100,128.215639,4.446364,0.523091,0.525188,3,1.673317,0.558481,0.028138,0.028015
12,1.00,50,65.369581,2.445981,0.516462,0.518321,4,1.192663,0.410437,0.025819,0.025984
11,0.50,300,382.339353,11.880153,0.493024,0.494486,5,19.824724,1.349544,0.012986,0.013271
10,0.50,200,253.810728,8.199413,0.492050,0.493194,6,3.198919,1.070016,0.013587,0.014683
9,0.50,100,125.197028,4.064062,0.487600,0.488609,7,3.781132,0.410744,0.014808,0.014941
8,0.50,50,63.682903,2.237938,0.486031,0.486698,8,1.222084,0.304803,0.015084,0.014736
7,0.10,300,373.320930,11.147065,0.449394,0.449906,9,4.070697,1.196459,0.004832,0.003952
6,0.10,200,255.532502,7.629337,0.447030,0.447279,10,1.790261,0.652441,0.004252,0.003185
5,0.10,100,128.916282,4.355064,0.438447,0.438436,11,1.943650,0.541200,0.003131,0.002754
4,0.10,50,65.306892,2.384462,0.428019,0.427987,12,1.377148,0.291356,0.001975,0.002123
0,0.01,50,50.901980,1.850666,0.426009,0.426009,13,1.119529,0.227663,0.000020,0.000005
1,0.01,100,101.908290,3.397713,0.426009,0.426009,13,4.325957,0.452761,0.000020,0.000005
2,0.01,200,245.672975,7.931800,0.426009,0.426009,13,4.774002,0.646739,0.000020,0.000005
3,0.01,300,379.626375,11.931986,0.426009,0.426009,13,4.753243,1.329901,0.000020,0.000005

Exception ignored in: <function ResourceTracker.__del__ at 0x76b6675a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x74eb87dae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ab5e23ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d603a3aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d15ff2aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x730dd49a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f9a506a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7861524aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7669c1caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x743484bae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71a42178a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78c59778e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7524ea7aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x799d059a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7dbc9189e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a8c7bfaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x784e426aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d5afc1a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77b89a0aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c22b69ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x798dd17a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77e2d58aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7603d23aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x783f9f7aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

Se puede apreciar claramente como el hiperparámetro más relevante de este modelo, por lo menos para este conjunto de datos es el ratio de aprendizaje. Este valor lo que hace es que el aprendizaje del modelo sea más o menos lento (cuanto mayor sea el valor mayor será la velocidad). Realmente lo que hace es que a los modelos bien clasificados se les de más o menos peso en el voto final, pero en la práctica tiene el efecto anteriormente comentado. Hay que tener en cuenta que un valor alto de este parámetro hace que tienda mucho al overfittin.  
  
El segunda parametro, el número de modelos, es mucho menos importante, por lo menos en este caso. Hay que tener en cuenta, que una buena forma de usar este hiperparámetro, es de manera inversamente proporcional al ratio de aprendizaje, ya que es conveniente con un ratio de aprendizaje alto, un número bajo de módelos evitaría el overfittin; y al revés también es conveniente.

### Histgram-Based Gradient Boosting

In [55]:
hb_gradient_boosting_pipeline= Pipeline([
    ('preprocessor', preprocesador),
    ('hist_gradient_boosting',HistGradientBoostingClassifier(random_state=semilla))
])

hb_gradient_boosting_param_grid = {
    'hist_gradient_boosting__max_iter': [100, 200, 300],
    'hist_gradient_boosting__learning_rate': [0.05, 0.1, 0.2], 
    'hist_gradient_boosting__max_depth': [3, 7]
}

hb_gradient_boosting_grid_search= optimize_with_grid_search(
    estimator=hb_gradient_boosting_pipeline,
    param_grid=hb_gradient_boosting_param_grid,
    X_train=X,
    y_train=y,
    cv_strategy=cv_strategy, 
    scoring_metric='f1_macro' 
)

mejor_hb_gradient_boosting= hb_gradient_boosting_grid_search.best_estimator_

--- Iniciando GridSearchCV para HistGradientBoostingClassifier ---
Fitting 25 folds for each of 18 candidates, totalling 450 fits
GridSearchCV para HistGradientBoostingClassifier completado en 990.84 segundos.

Mejores Parámetros encontrados para HistGradientBoostingClassifier:
{'hist_gradient_boosting__learning_rate': 0.2, 'hist_gradient_boosting__max_depth': 7, 'hist_gradient_boosting__max_iter': 300}

Mejor Puntuación Media CV (score): 0.7165

Resumen de Resultados GridSearchCV para HistGradientBoostingClassifier:

,param_hist_gradient_boosting__learning_rate,param_hist_gradient_boosting__max_depth,param_hist_gradient_boosting__max_iter,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
17,0.20,7,300,64.989852,2.017696,0.716492,0.740753,1,3.323418,0.707332,0.005709,0.002429
16,0.20,7,200,46.137199,1.717562,0.707956,0.724148,2,2.096093,0.286854,0.005645,0.002329
11,0.10,7,300,68.425754,2.410054,0.699500,0.712334,3,2.874813,0.495427,0.005505,0.001948
14,0.20,3,300,54.047993,1.283497,0.692717,0.699210,4,2.824364,0.210616,0.005460,0.002909
15,0.20,7,100,25.393773,0.972226,0.691099,0.704210,5,1.585042,0.158686,0.005433,0.002974
10,0.10,7,200,48.570564,1.723085,0.689694,0.701752,6,2.273343,0.295728,0.005760,0.002610
13,0.20,3,200,37.715379,0.898291,0.683846,0.690020,7,1.488222,0.141328,0.005913,0.002803
5,0.05,7,300,74.703214,2.354806,0.682111,0.692489,8,2.454429,0.396535,0.005614,0.002543
8,0.10,3,300,55.943269,1.308139,0.676468,0.681525,9,2.499270,0.175589,0.005482,0.002458
9,0.10,7,100,27.674062,1.027287,0.670914,0.681538,10,1.527473,0.161649,0.005265,0.002326
4,0.05,7,200,53.757985,1.774056,0.668930,0.679583,11,2.656155,0.322639,0.005266,0.002777
12,0.20,3,100,21.096711,0.652227,0.664642,0.670895,12,1.339817,0.119099,0.006362,0.002553
7,0.10,3,200,38.393641,0.900563,0.662427,0.668835,13,2.330566,0.145889,0.005061,0.002345
2,0.05,3,300,56.326666,1.303339,0.646312,0.652938,14,3.124691,0.228034,0.004423,0.001983
3,0.05,7,100,30.273436,1.059722,0.626799,0.639924,15,2.069674,0.216960,0.003639,0.002769
6,0.10,3,100,22.366758,0.649745,0.620793,0.628072,16,1.840769,0.129953,0.004085,0.002235
1,0.05,3,200,39.575352,0.982315,0.618427,0.625618,17,2.093016,0.180467,0.004510,0.001922
0,0.05,3,100,21.964045,0.657083,0.562677,0.567252,18,1.367257,0.123842,0.006115,0.002413

Con lo que se aprecia con los datos obtenidos, parece que el hiperparámetro más relevante para este modelo, por lo menos en este caso es el ratio de aprendizaje, que básicamente funciona igual que en el modelo anterior. Aunque aquí no parece haber tanta diferencia como en el anterior entre los distintos valores, anque seguramente sea porque he elegido valores mucho más bajos; y lo he hecho porque por lo que me he informado, este modelo tiende mucho más al overfittin que el anterior, por lo que he decidido que no sería bueno aumentarlo todavía más.  
  
Por lo que puedo ver en los datos, diría que el segundo hiperparámetro más relevante es el número máximo de iteraciones del modelo, aunque no queda tan claro como en otros casos. Este parámetro es muy parecido al 'n_estimators' de otros ensembles, ya que marca el número máximo de arbles que se pueden generar. Para este conjunto de datos parece ser que suele ser mejor un número más alto.  
  
Por último, el hiperparámetro que parece ser menos relevante es al profundidad máxima de cada árbol, lo cual choca con lo que se ha visto en anteriores ensembles que usan árboles, donde este parámetro tiene mucho peso. Esto puede ser divido a que de la manera que funciona este modelo no necesita que los árboles tenga demasiada profundidad.

### Stacking Classifier

In [ ]:
estimators_base = [
    ('log_reg', LogisticRegression(random_state=semilla, solver='liblinear', max_iter=1000)), 
    ('dt', DecisionTreeClassifier(random_state=semilla, max_depth=5)), 
]

tacking_model = StackingClassifier(
    estimators=estimators_base, 
    final_estimator=LogisticRegression(random_state=semilla, solver='liblinear'), 
    n_jobs=-1,
    passthrough=False 
)

stacking_pipeline = Pipeline([
    ('preprocessor', preprocesador),
    ('stacking', stacking_model)
])

stacking_param_grid = {
    # Hiperparámetros para el meta-estimador (final_estimator__C)
    'stacking__final_estimator__C': [0.1, 1.0, 10.0], 
    # Hiperparámetros para el estimador base Regresión Logística (log_reg__C)
    'stacking__log_reg__C': [0.1, 1.0], 
    # Hiperparámetros para el estimador base Árbol de Decisión (dt__max_depth)
    'stacking__dt__max_depth': [3, 7]
}

stacking_grid_search = optimize_with_grid_search(
    estimator=stacking_pipeline,
    param_grid=stacking_param_grid,
    X_train=X, 
    y_train=y, 
    cv_strategy=cv_strategy,
    scoring_metric='f1_macro'
)

mejor_stacking = stacking_grid_search.best_estimator_

--- Iniciando GridSearchCV para StackingClassifier ---
Fitting 25 folds for each of 12 candidates, totalling 300 fits

Exception ignored in: <function ResourceTracker.__del__ at 0x731ce42aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
/var/data/python/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(
Exception ignored in: <function ResourceTracker.__del__ at 0x7ca17a4a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x776369aa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x72422238e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x719c9a5aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7dabff4aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a4193aa2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b39b6eaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e22997a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d127b7b2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x789563d8e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78cd8ada2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x72ff6aa9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x722cd74aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a3ce48aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x761626a9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x720654da6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7449f1ca2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70ff622aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70a6b65a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7fc2818aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x759ab9da2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x732a11da6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d6c2e4aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d7f2ee9e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x70d7524aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75d2ca9ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

GridSearchCV para StackingClassifier completado en 503.44 segundos.

Mejores Parámetros encontrados para StackingClassifier:
{'stacking__dt__max_depth': 7, 'stacking__final_estimator__C': 10.0, 'stacking__log_reg__C': 1.0}

Mejor Puntuación Media CV (score): 0.7786

Resumen de Resultados GridSearchCV para StackingClassifier:

,param_stacking__dt__max_depth,param_stacking__final_estimator__C,param_stacking__log_reg__C,mean_fit_time,mean_score_time,mean_test_score,mean_train_score,rank_test_score,std_fit_time,std_score_time,std_test_score,std_train_score
11,7,10.0,1.0,39.029529,0.646609,0.778601,0.785607,1,9.863107,0.380632,0.004888,0.001756
9,7,1.0,1.0,41.715788,0.923415,0.778469,0.785489,2,3.629094,0.438135,0.004917,0.001791
5,3,10.0,1.0,31.336768,0.855406,0.777475,0.783040,3,3.431959,0.396229,0.005160,0.001766
3,3,1.0,1.0,33.754698,0.850826,0.777241,0.782908,4,2.817565,0.304551,0.005233,0.001791
7,7,0.1,1.0,41.262674,1.031917,0.776359,0.784052,5,3.841579,0.347574,0.005054,0.001870
1,3,0.1,1.0,32.272758,0.722276,0.775699,0.781205,6,2.485039,0.230203,0.005041,0.001576
4,3,10.0,0.1,24.519780,0.806293,0.729667,0.736457,7,2.332491,0.313057,0.005776,0.001672
10,7,10.0,0.1,39.465408,0.900198,0.729458,0.737594,8,5.505020,0.341244,0.005950,0.001674
2,3,1.0,0.1,23.923283,0.988996,0.729188,0.735848,9,2.710649,0.469114,0.005729,0.001765
8,7,1.0,0.1,36.135163,0.983616,0.728896,0.737145,10,3.163373,0.395119,0.006028,0.001610
0,3,0.1,0.1,26.772951,0.917150,0.724527,0.730928,11,2.836878,0.323693,0.005997,0.001903
6,7,0.1,0.1,36.609151,0.805107,0.724116,0.731754,12,3.018740,0.302092,0.006041,0.001825

Exception ignored in: <function ResourceTracker.__del__ at 0x7715dd2aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7dc949aaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7dd96cba6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x722531faa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b318879a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d8f3409e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a35e6baa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7d6f3429e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77b29809e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7bf61499e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7e10184a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7ad9c3eaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7bb64adaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7674ce9ae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x73688c5a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x76f2b7eaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x72d673caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7a03fd3aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7f22242aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b70b319a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x78ceb3ba6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x75b1cdcaa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7824ef4aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

En este caso, lo primero será explicar un poco del modelo, y es que en este caso, los modelos básicos (de la capa 1) que he escogido son la regresión logistica y el árbol de decisión. El modelo que he elegido como estimador final (capa 2) ha sido también la regresión logística; ya que por lo que he visto es muy común usar este modelo para ambas capas; además de que como lo he implementado como tal, he pensado que estaría bien utilizarlo aqui. Hay un hiperparámetro por cada modelo usado.  
  
Con esto dicho, parece ser que el hiperparámetro más relevante en este caso es el parámetro C de regulación, pero del modelo de regresión logistica de la capa 1, es decir el básico. Esto seguramente se deba a que sea su estimación la más correcta y la que más se tenga en cuenta en la segunda capa.  
  
Lo anterior parece tener más sentido tras comprobar el hiperparámetro del otro modelo básico, la profundidad m-axima del árbol (en este caso solo he elegido usar un hiperparámetro para el árbol para no complicar en exceso el modelo). No parece tener demasiado peso sobre el score, ya que los distintos valores aparecen con los mejores scores y con los peores, por lo que creo que este es el hiperparámetro más irrelevante del modelo en este caso.  
  
Por último, el hiperparámetro del modelo del estiamdor final, que es el mismo que en el anterior modelo de la capa 1; ya que también es una regresión logistica, solo que en este caso le he dado un posible valor más alto, ya que los modelos de la capa 2 tienden menos a sobre ajustar. Por lo que se puede apreciar en los datos de salida, parece que va mejor en valores altos, y como se pede apreciar no esta ligado a un incrementeo significativo del overfitting.

## 3. Selección y evaluación del modelo final

Aunque viendo los resultados y las conclusiones del aparatado anterior, ya se puede más o menos ver cuál es el mejor modelo para este conjunto de datos, voy a realizar las mismas pruebas que figuran en el cuaderno de ejemplo de esta practica.

### Identificación del mejor modelo

In [63]:
search_results_dict = {
    "Naive Bayes": nb_search_results,
    "Arbol de decision": arbol_grid_search,
    "Bagging": bagging_search_results,
    "Random Forest": rf_grid_search,
    "Adaptive Boost": adaptive_boost_grid_search,
    "Histgram-Based Gradient Boost": hb_gradient_boosting_grid_search,
    "Stacking Classifier": stacking_grid_search
}

# Encontrar el mejor modelo basado en best_score_
best_model_name_cv = None
best_cv_score = -1
best_search_object_cv = None

print(f"--- Selección basada en Validación Cruzada ({'f1_macro'}) ---")
for name, search_result in search_results_dict.items():
    print(f"Modelo: {name}, Mejor {'f1_macro'} (CV): {search_result.best_score_:.4f}")
    if search_result.best_score_ > best_cv_score:
        best_cv_score = search_result.best_score_
        best_model_name_cv = name
        best_search_object_cv = search_result

print(f"\nModelo seleccionado (mejor CV): {best_model_name_cv}")
print(f"Mejores parámetros encontrados: {best_search_object_cv.best_params_}")
print(f"Mejor puntuación media en CV: {best_search_object_cv.best_score_:.4f}")

--- Selección basada en Validación Cruzada (f1_macro) ---
Modelo: Naive Bayes, Mejor f1_macro (CV): 0.7549
Modelo: Arbol de decision, Mejor f1_macro (CV): 0.6423
Modelo: Bagging, Mejor f1_macro (CV): 0.6539
Modelo: Random Forest, Mejor f1_macro (CV): 0.6534
Modelo: Adaptive Boost, Mejor f1_macro (CV): 0.5477
Modelo: Histgram-Based Gradient Boost, Mejor f1_macro (CV): 0.7165
Modelo: Stacking Classifier, Mejor f1_macro (CV): 0.7786

Modelo seleccionado (mejor CV): Stacking Classifier
Mejores parámetros encontrados: {'stacking__dt__max_depth': 7, 'stacking__final_estimator__C': 10.0, 'stacking__log_reg__C': 1.0}
Mejor puntuación media en CV: 0.7786

Con esta comprobación se puede ver como el mejor modelo, al menos para el conjunto de entrenamiento es el Stacking Classifier.

### Comparación de modelos en Test

El problema de este apartado, es que no puedo comparar los modelos con el conjunto de Test (como lo hace en el cuaderno de ejemplo), ya que no tengo la columna 'abandono' en este dataframe, para comprobarlo tendré que hacerlo a través de Kaggle. A si que la comprobación de este apartado la tendría que hacer con el conjunto de train, pero no tendría sentido, ya que simplemente me daría el modelo que mejor sobre ajusta, no el modelo que mejor rinde.  
  
Lo que voy a hacer es generar predicciones para el Test con el mejor modelo de Stacking Classifier, Naive Bayes y Histgram-Based Gradient Boost (los 3 modelos que mejor score han obtenido en las purebas de validación). Para ello me voy a valer de la función que usé en la practica 1 para producir los archivos .csv con las predicciones.

In [ ]:
def generar_archivo_csv(pipeline, df, nombre_archivo):

    # Guardo la columna par luego insertarla en el archivo de entrega (ya que lo elimino en la pipeline)
    ids = df['id'].copy() 

    # Predigo la columna 'abandono'
    predicciones_abandono = pipeline.predict(df)
    
    # Construyo el dataframe con los resultados y el id
    df_submission = pd.DataFrame({
        'id': ids,
        'abandono': predicciones_abandono
    })
    
    # Me aseguro de que el tipo de dato generado para la predicción de 'abandono' es int
    df_submission['abandono'] = df_submission['abandono'].astype(int)

    # Genero el csv
    df_submission.to_csv(nombre_archivo, index=False)

    return df_submission

In [77]:
nombre='Stacking_kaggle.csv'

mejor_stacking.fit(X,y)
generar_archivo_csv(mejor_stacking, df_test, nombre)

                  id  abandono
0     AB-2019-FEM764         1
1     TO-2018-ALL744         0
2     AB-2018-ZSD099         0
3     CR-2019-TCS733         0
4     CR-2018-VBV597         1
...              ...       ...
9582  AB-2019-AAM365         0
9583   AB-2019-MC507         0
9584  AB-2019-MNC716         1
9585  AB-2018-ICH450         0
9586   CU-2019-CL671         0

[9587 rows x 2 columns]

Este modelo ha conseguido en el test (viendolo a través de Kaggle) 0.6636 de score.

In [78]:
nombre='Naive_Bayes_kaggle.csv'

mejor_nb.fit(X,y)
generar_archivo_csv(mejor_nb, df_test, nombre)

                  id  abandono
0     AB-2019-FEM764         1
1     TO-2018-ALL744         0
2     AB-2018-ZSD099         0
3     CR-2019-TCS733         0
4     CR-2018-VBV597         1
...              ...       ...
9582  AB-2019-AAM365         0
9583   AB-2019-MC507         0
9584  AB-2019-MNC716         1
9585  AB-2018-ICH450         0
9586   CU-2019-CL671         0

[9587 rows x 2 columns]

Exception ignored in: <function ResourceTracker.__del__ at 0x75beb1caa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x71b55f1a6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77c6c5da6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7895b6fae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x767531da6160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x77badd4aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x785ee2b9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7c43e22aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7fc2896a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7677ecb9a160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b00fd98e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

Este modelo ha conseguido en el test (viendolo a través de Kaggle) 0.6424 de score.

In [ ]:
nombre='HB_Gradient_Boost_kaggle.csv'

mejor_hb_gradient_boosting.fit(X,y)
generar_archivo_csv(mejor_hb_gradient_boosting, df_test, nombre)

                  id  abandono
0     AB-2019-FEM764         1
1     TO-2018-ALL744         0
2     AB-2018-ZSD099         0
3     CR-2019-TCS733         0
4     CR-2018-VBV597         1
...              ...       ...
9582  AB-2019-AAM365         0
9583   AB-2019-MC507         0
9584  AB-2019-MNC716         0
9585  AB-2018-ICH450         0
9586   CU-2019-CL671         0

[9587 rows x 2 columns]

Exception ignored in: <function ResourceTracker.__del__ at 0x79cfd869e160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7bb6664a2160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x765d91bae160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes
Exception ignored in: <function ResourceTracker.__del__ at 0x7b873b2aa160>
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 77, in __del__
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 86, in _stop
  File "/usr/lib/python3.12/multiprocessing/resource_tracker.py", line 111, in _stop_locked
ChildProcessError: [Errno 10] No child processes

Este modelo ha conseguido en el test (viendolo a través de Kaggle) 0.5685 de score.

Después de comprobar los scores obtenidos en el Test de los tres mejores modelos en el Train, puedo concluir que el mejor modelo de los que he implementado es el modelo Stacking Classifier con un 0.6636.